### POST 새 댓글 생성
POST http://localhost:8080/api/articles/3/comments
Content-Type: application/json

{
  "body": "댓글 내용2"
}

### GET 댓글 ID로 조회
GET http://localhost:8080/api/comments/1


### PUT 댓글 수정
PUT http://localhost:8080/api/comments/1
Content-Type: application/json

{
  "body": "댓글 수정"
}

### DELETE 댓글 삭제
DELETE http://localhost:8080/api/comments/3

### 게시글과 댓글 정보를 한번에 조회
GET http://localhost:8080/api/articles/3/comments